### ISSUE TITLE
precompiled bin not working after flashing M5core

### ISSUE THREAD

**Issue by Netoperz** [botofancalin/M5Stack-MultiApp-Advanced#11]
M5stack core.
downloaded the .bin precompiled, and flashed with the tool 

black screen nothing happens...

What more should i do ? 
Should i copy some files to the sd card, what files ?

I'm a bit lost

**Comment by botofancalin** [comment]
Clone the repository, compile and upload to M5Stack.
You can find the instructions on the repository main page.
That's the best solution.
