### ISSUE TITLE
Add my graph please?

### ISSUE THREAD

**Issue by foxpdll** [botofancalin/M5Stack-MultiApp-Advanced#12]
I had write simple graphShower for https://narodmon.ru data
Can you add my code to youre firmware, please?
[FoxGraph.zip](https://github.com/botofancalin/M5Stack-MultiApp-Advanced/files/2653110/FoxGraph.zip)

**Comment by botofancalin** [comment]
Added. 
For more contributions, you can start a pull request with your mods to be added to firmware.
You can also add your name on your app.
