### ISSUE TITLE
Invert Color

### ISSUE THREAD

**Issue by mltongca** [botofancalin/M5Stack-MultiApp-Advanced#17]
When the MultiApp starts, the display shows invert color. It seems a common problem on other M5 Stack apps recently.

**Comment by botofancalin** [comment]
That problem may be caused by a change on new M5Stack hardware. They may use a different LCD variant that need a different driver setting.

**Comment by mltongca** [comment]
M5 Stack apps on Arduino IDE can resolve the invert color after recompilation probably using different/updated default driver setting as you identified.
