### ISSUE TITLE
Missing Wire Initialisation in I2CScannerCllass

### ISSUE THREAD

**Issue by ZeTibofParis** [botofancalin/M5Stack-MultiApp-Advanced#2]
**Describe the bug**
I2C Scan is not working because Wire Object is not initialiazed correctly 

To correct it add  Wire.begin(); after M5m.update(); on line 5 in the I2CScanner.cpp file

**Comment by ZeTibofParis** [comment]
@

**Comment by botofancalin** [comment]
Bug fixed on latest commit. Added wire initialization at startup.
