### ISSUE TITLE
I2C Scanner not working

### ISSUE THREAD

**Issue by ZeTibofParis** [botofancalin/M5Stack-MultiApp-Advanced#3]
I2C Scanner not working

There is a missing initialization in the   I2CScannerClass::Run() function in the  I2CScanner.cpp  file.
In order to correct the bug, just add         Wire.begin(); after the line 5 : M5m.update(); 
@botofancalin

**Comment by botofancalin** [comment]
TNX for reporting. 
Check the latest commit. 
I Added the wire initialization to I2C setup on M5StackMod class.
