### ISSUE TITLE
New version compilation results

### ISSUE THREAD

**Issue by Kabron287** [botofancalin/M5Stack-MultiApp-Advanced#7]
M5StackMod initializing...[E][sd_diskio.cpp:739] sdcard_mount(): f_mount failed 0x(3)
E (705) SPIFFS: mount failed, -10025
[E][SPIFFS.cpp:47] begin(): Mounting SPIFFS failed! Error: -1
OK
[E][Preferences.cpp:330] getUShort(): nvs_get_u16 fail: light NOT_FOUND
and nothing more...

any ideas?

**Comment by botofancalin** [comment]
1. Make sure you use the latest Espressif32 platform on PlatformIO
2. Make sure the SDcard is connected to M5Stack
3. Modify the brightness to any value then that serial error will go away.
