### ISSUE TITLE
No wifi connection

### ISSUE THREAD

**Issue by dmeylman** [botofancalin/M5Stack-MultiApp-Advanced#8]
I can not get the WIFI connection to work. Any advice? Thanks

**Comment by botofancalin** [comment]
You can use esp8266 Smartconfig app from the phone or WPS options from "System->Wifi Settings" menu to setup a wifi connection to your Wifi
![image](https://raw.githubusercontent.com/botofancalin/M5Stack-MultiApp-Advanced/master/MultiAppImgs/WifiOptions.jpg)

**Comment by dmeylman** [comment]
Thanks a lot for the help. Works and connected now. The only problem now is connecting to Wunderground. It seems my API key is wrong...Any suggestion? Thanks again
![img_3811](https://user-images.githubusercontent.com/32586435/42730466-b5f52000-87a9-11e8-8c51-47037ec499dc.JPG)
![img_3814](https://user-images.githubusercontent.com/32586435/42730467-b60d63a4-87a9-11e8-862b-96204de64597.JPG)

**Comment by botofancalin** [comment]
Enter your wunderground api key on WeatherParams.txt then will work just fine

**Comment by dmeylman** [comment]
Yes, I did but still won't detect the temps. Having the same issue with my other projects. Anyway, Thanks for the quick reply.

**Comment by botofancalin** [comment]
The WeatherStation app read the data from wunderground.com
To be able to get that data, you must enter your data on the WeatherParams.txt file on the sdcard.
You need a wunderground account to get the api key.
Use underscore instead space for city names.

Here is an example of how that params should look like:

![image](https://user-images.githubusercontent.com/32721615/42744499-acb7b976-88d5-11e8-8695-f787484c116d.png)

![image](https://user-images.githubusercontent.com/32721615/42744535-f4fdd18e-88d5-11e8-97ec-184b5a53bbac.png)

**Comment by dmeylman** [comment]
Still cannot get any temp readings but the date and time is right. Maybe there something wrong with my Wunderground acct. I've even tried exactly whats in your example but still no luck. Thanks again for the help.

**Comment by dmeylman** [comment]
I found out they're no longer provide a free API key.
